# Generated by Django 6.0.1 on 2026-02-04 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_event_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('parliamentarian', 'Parliamentarian'), ('chaplain', 'Chaplain'), ('historian', 'Historian'), ('sergeant_at_arms', 'Sergeant at Arms'), ('board_member', 'Board Member'), ('other', 'Other Position')], max_length=50)),
                ('position_custom', models.CharField(blank=True, help_text="Custom position title (if 'Other' is selected)", max_length=100, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, help_text='Brief biography or background', null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='Upload profile photo', null=True, upload_to='leadership/')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Currently serving in this position')),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chapter Leader',
                'verbose_name_plural': 'Chapter Leadership',
                'ordering': ['display_order', 'position'],
            },
        ),
    ]
