# Generated by Django 4.2.28 on 2026-02-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_memberprofile_duespayment_document_announcement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterleadership',
            name='user',
        ),
    ]
