# Generated by Django 4.2.28 on 2026-02-04 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0007_photo_photocomment_photoalbum_photo_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique invitation code', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='Email address this code is assigned to', max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('member_number', models.CharField(blank=True, help_text='National member number (if applicable)', max_length=50)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this invitation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_created', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation Code',
                'verbose_name_plural': 'Invitation Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
