# Generated by Django 4.2.28 on 2026-02-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_category_alter_chapterleadership_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('financial', 'Financial'), ('non_financial', 'Non Financial'), ('financial_life_member', 'Financial Life Member'), ('non_financial_life_member', 'Non Financial Life Member'), ('new_member', 'New Member'), ('suspended', 'Suspended')], default='financial', max_length=30),
        ),
    ]
