# Generated by Django 4.2.28 on 2026-02-05 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0011_announcementview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterleadership',
            name='position',
            field=models.CharField(choices=[('president', 'President'), ('vice_president_1st', '1st Vice President'), ('vice_president_2nd', '2nd Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('parliamentarian', 'Parliamentarian'), ('chaplain', 'Chaplain'), ('historian', 'Historian'), ('sergeant_at_arms', 'Sergeant at Arms'), ('board_member', 'Board Member'), ('other', 'Other Position')], max_length=50),
        ),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(help_text='Stripe PaymentIntent ID', max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, default='', help_text='Stripe Charge ID', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in cents', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_type', models.CharField(choices=[('monthly_dues', 'Monthly Dues'), ('semester_dues', 'Semester Dues'), ('annual_dues', 'Annual Dues'), ('fine', 'Fine'), ('house_charge', 'House Charge'), ('event_fee', 'Event Fee'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('card_last_four', models.CharField(blank=True, default='', max_length=4)),
                ('card_brand', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment succeeded', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if payment failed')),
                ('dues_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payment', to='pages.duespayment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payments', to='pages.memberprofile')),
            ],
            options={
                'verbose_name': 'Stripe Payment',
                'verbose_name_plural': 'Stripe Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_publishable_key', models.CharField(help_text='Stripe Publishable Key', max_length=255)),
                ('stripe_secret_key', models.CharField(help_text='Stripe Secret Key (encrypted)', max_length=255)),
                ('stripe_account_id', models.CharField(blank=True, default='', help_text='Stripe Account ID', max_length=255)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_account_last_four', models.CharField(blank=True, default='', max_length=4)),
                ('bank_routing_number', models.CharField(blank=True, default='', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable online payments')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Use Stripe test keys')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treasurer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Configuration',
                'verbose_name_plural': 'Stripe Configuration',
            },
        ),
    ]
