# Generated by Django 4.2.28 on 2026-02-05 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0012_alter_chapterleadership_position_stripepayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(help_text='Twilio Account SID', max_length=255)),
                ('auth_token', models.CharField(help_text='Twilio Auth Token (will be encrypted in production)', max_length=255)),
                ('twilio_phone_number', models.CharField(help_text='Twilio phone number (e.g., +1234567890)', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Enable/disable SMS alerts')),
                ('is_test_mode', models.BooleanField(default=True, help_text="Test mode only logs SMS, doesn't send")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='twilio_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Twilio Configuration',
                'verbose_name_plural': 'Twilio Configurations',
            },
        ),
        migrations.CreateModel(
            name='SMSPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opted_in', models.BooleanField(default=False, help_text='Member has opted in to SMS alerts')),
                ('phone_number', models.CharField(blank=True, default='', help_text="Member's phone number for SMS", max_length=20)),
                ('receive_announcements', models.BooleanField(default=False)),
                ('receive_messages', models.BooleanField(default=False)),
                ('receive_dues_reminders', models.BooleanField(default=False)),
                ('receive_event_alerts', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (e.g., 22:00)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours (e.g., 08:00)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_opted_in', models.DateTimeField(blank=True, null=True)),
                ('last_opted_out', models.DateTimeField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_preference', to='pages.memberprofile')),
            ],
            options={
                'verbose_name': 'SMS Preference',
                'verbose_name_plural': 'SMS Preferences',
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('sms_type', models.CharField(choices=[('announcement', 'Announcement'), ('message', 'Direct Message'), ('dues_reminder', 'Dues Reminder'), ('event_alert', 'Event Alert'), ('admin', 'Admin Notification')], max_length=20)),
                ('twilio_sid', models.CharField(blank=True, default='', help_text='Twilio message SID', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('test', 'Test Mode (Not Sent)')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('triggered_by', models.CharField(blank=True, default='', help_text='admin_manual, announcement, message, etc.', max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related Announcement/Message/Event', null=True)),
                ('related_object_type', models.CharField(blank=True, default='', help_text='Announcement, Message, Event, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='pages.memberprofile')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', '-created_at'], name='pages_smslo_member__3a2bf1_idx'), models.Index(fields=['status', '-created_at'], name='pages_smslo_status_e7076c_idx'), models.Index(fields=['sms_type', '-created_at'], name='pages_smslo_sms_typ_a6ec52_idx')],
            },
        ),
    ]
