# Generated by Django 4.2.28 on 2026-02-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_twilioconfiguration_smspreference_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='duespayment',
            name='custom_type',
            field=models.CharField(blank=True, default='', help_text="Custom bill type description when payment_type is 'other'", max_length=100),
        ),
    ]
