# Generated by Django 4.2.28 on 2026-02-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_duespayment_custom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('social_action', 'Social Action'), ('education', 'Education'), ('business', 'Business'), ('sigma_beta_club', 'Sigma Beta Club'), ('sigma_wellness', 'Sigma Wellness'), ('other', 'Other')], default='other', help_text='Select the type of event', max_length=50),
        ),
    ]
