# Generated by Django 4.2.28 on 2026-02-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_cart_order_product_orderitem_cartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_officer',
            field=models.BooleanField(default=False, help_text='Is this member an officer with admin privileges?'),
        ),
    ]
