# Generated by Django 4.2.28 on 2026-02-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_memberprofile_is_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='marked_for_removal_date',
            field=models.DateTimeField(blank=True, help_text='Date member was marked for removal - gives 90 day window to resolve', null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='removal_reason',
            field=models.CharField(blank=True, default='', help_text="Reason for marking for removal (e.g., 'Not in HQ member list')", max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('meeting_minutes', 'Meeting Minutes'), ('calendar', 'Calendar'), ('manual', 'Officer Manual'), ('bylaws', 'Bylaws & Constitution'), ('financial', 'Financial Documents'), ('forms', 'Forms & Templates'), ('officer_only', 'Officer Only'), ('other', 'Other')], max_length=50),
        ),
    ]
