# Generated by Django 4.2.28 on 2026-02-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_add_member_removal_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='marked_for_removal_date',
            field=models.DateTimeField(blank=True, help_text='Date member was marked for dues payment - gives 90 day window to pay national/local dues', null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='removal_reason',
            field=models.CharField(blank=True, default='', help_text="Reason for marking (e.g., 'Not on current HQ list - requires dues verification')", max_length=200),
        ),
    ]
