# Generated by Django 4.2.28 on 2026-02-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_memberprofile_marked_for_removal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('GN', 'General'), ('OF', 'Official Chapter Business'), ('EV', 'Event Related'), ('FI', 'Financial'), ('CM', 'Committee')], default='GN', max_length=2),
        ),
        migrations.AddField(
            model_name='message',
            name='priority',
            field=models.CharField(choices=[('LO', 'Low'), ('NR', 'Normal'), ('HI', 'High'), ('UR', 'Urgent')], default='NR', max_length=2),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('SE', 'Sent'), ('RD', 'Read'), ('AR', 'Archived'), ('DE', 'Deleted')], default='SE', max_length=2),
        ),
    ]
