# Generated by Django 4.2.28 on 2026-02-14 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_cart_session_key_alter_order_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Primary question or keyword (5-500 chars)', max_length=500, validators=[django.core.validators.MinLengthValidator(5)])),
                ('keywords', models.TextField(help_text="Comma-separated keywords for searching (e.g., 'phi beta sigma, fraternity, brotherhood')")),
                ('answer', models.TextField(help_text='Public answer text. NEVER include private/member data.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('category', models.CharField(choices=[('about', 'About the Fraternity'), ('history', 'History & Traditions'), ('membership', 'Membership'), ('events', 'Events & Programs'), ('contact', 'Contact Information'), ('values', 'Values & Mission'), ('faq', 'Frequently Asked Questions'), ('other', 'Other')], default='faq', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive answers won't be shown by chatbot")),
                ('confidence_threshold', models.IntegerField(default=30, help_text='Minimum confidence score (0-100) to display this answer')),
                ('internal_note', models.TextField(blank=True, help_text='Internal notes (not visible to public)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', help_text='Admin user who created this entry', max_length=100)),
            ],
            options={
                'verbose_name': 'Public Answer',
                'verbose_name_plural': 'Public Answers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='pages_publi_is_acti_40b0bb_idx'), models.Index(fields=['category', 'is_active'], name='pages_publi_categor_1e9a13_idx')],
            },
        ),
    ]
