# Generated by Django 4.2.28 on 2026-02-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_publicanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='program',
            field=models.CharField(blank=True, choices=[('', 'No Program'), ('bbb', 'Bigger & Better Business'), ('education', 'Education'), ('social_action', 'Social Action'), ('sigma_beta', 'Sigma Beta Club')], default='', help_text='Which fraternity program this album belongs to', max_length=20),
        ),
    ]
