# Generated by Django 4.2.28 on 2026-02-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_add_program_to_photoalbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover photo for profile page (recommended: 820x312)', null=True, upload_to='member_covers/'),
        ),
    ]
