# Generated by Django 4.2.28 on 2026-02-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_add_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text="Member's birthday", null=True),
        ),
    ]
