# Generated by Django 4.2.28 on 2026-02-20 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0026_add_birthday_to_memberprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Phi Beta Sigma Fraternity, Inc', help_text='Main organization name displayed in header', max_length=200)),
                ('chapter_name', models.CharField(default='Nu Gamma Sigma Chapter', help_text='Chapter name displayed below organization name', max_length=200)),
                ('chapter_logo', models.ImageField(blank=True, help_text='Chapter-specific logo (optional)', null=True, upload_to='site_branding/')),
                ('pbs_seal', models.ImageField(blank=True, help_text='Phi Beta Sigma seal/logo displayed in header', null=True, upload_to='site_branding/')),
                ('favicon', models.ImageField(blank=True, help_text='Site favicon (browser tab icon)', null=True, upload_to='site_branding/')),
                ('facebook_url', models.URLField(blank=True, default='', help_text='Facebook page URL')),
                ('instagram_url', models.URLField(blank=True, default='', help_text='Instagram profile URL')),
                ('twitter_url', models.URLField(blank=True, default='', help_text='Twitter/X profile URL')),
                ('email_address', models.EmailField(blank=True, default='', help_text='Contact email address', max_length=254)),
                ('footer_text', models.CharField(default='© 2026 Phi Beta Sigma Fraternity, Incorporated. Nu Gamma Sigma Chapter', help_text='Footer copyright/text', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
