# Generated by Django 4.2.28 on 2026-02-21 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0027_add_site_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterHistorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section heading (e.g., "Our Beginning")', max_length=200)),
                ('section_type', models.CharField(choices=[('intro', 'Introduction'), ('founding', 'Founding Story'), ('milestones', 'Milestones & Achievements'), ('leadership', 'Leadership Legacy'), ('community', 'Community Service'), ('national', 'National Connection'), ('custom', 'Custom Section')], default='custom', help_text='Type of content section', max_length=20)),
                ('content', models.TextField(help_text='Section content (supports basic HTML formatting)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which sections appear (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive sections will not display on the page')),
                ('image', models.ImageField(blank=True, help_text='Optional image for this section', null=True, upload_to='history_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_sections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chapter History Section',
                'verbose_name_plural': 'Chapter History Sections',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
