# Generated by Django 4.2.28 on 2026-02-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_chapterhistorysection'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_us_text',
            field=models.TextField(blank=True, default='', help_text='Main "About the Chapter" text displayed on the About page and home page modal'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='chapter_legacy',
            field=models.TextField(blank=True, default='', help_text='Chapter legacy/history summary text'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='chapter_president',
            field=models.CharField(blank=True, default='', help_text='Name of the current chapter president', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='chapter_region',
            field=models.CharField(blank=True, default='', help_text='Regional affiliation (e.g., Great Lakes Region)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='charter_date',
            field=models.DateField(blank=True, help_text='Date the chapter was chartered', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='chatbot_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable the chatbot widget site-wide'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='chatbot_rate_limit',
            field=models.PositiveIntegerField(default=30, help_text='Maximum chatbot requests per minute per IP address'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='chatbot_welcome_message',
            field=models.TextField(blank=True, default="I'm here to help answer questions about our fraternity. You can ask me about our history, membership, events, values, and more.", help_text='Welcome message displayed when chatbot opens'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='city_state',
            field=models.CharField(blank=True, default='', help_text='City and state (e.g., Belleville, Illinois)', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='dark_mode_default',
            field=models.BooleanField(default=False, help_text='Make dark mode the default for visitors'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mailing_address',
            field=models.CharField(blank=True, default='', help_text='Official chapter mailing address', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='maintenance_message',
            field=models.CharField(blank=True, default='We are currently performing scheduled maintenance. Please check back soon.', help_text='Message to display during maintenance mode', max_length=500),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Put the site in maintenance mode (only staff can access)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meeting_location',
            field=models.CharField(blank=True, default='', help_text='Where the chapter holds meetings', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meeting_schedule',
            field=models.CharField(blank=True, default='', help_text='When the chapter meets (e.g., First Saturday of each month at 10 AM)', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='Site description for search engines (recommended 150-160 characters)', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', help_text='SEO keywords (comma-separated)', max_length=500),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='mission_statement',
            field=models.TextField(blank=True, default='', help_text='Chapter mission statement'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Default image for social media sharing', null=True, upload_to='site_branding/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pbs_hq_url',
            field=models.URLField(blank=True, default='https://phibetasigma1914.org/', help_text='Link to Phi Beta Sigma national headquarters website'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Chapter phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='primary_color',
            field=models.CharField(blank=True, default='#0047AB', help_text='Primary brand color (hex code, e.g., #0047AB)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='secondary_color',
            field=models.CharField(blank=True, default='#003380', help_text='Secondary brand color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='service_areas',
            field=models.CharField(blank=True, default='', help_text='Areas served by the chapter (e.g., St. Clair County, Madison County)', max_length=500),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_boutique',
            field=models.BooleanField(default=True, help_text='Show the merchandise boutique section'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_events',
            field=models.BooleanField(default=True, help_text='Show the events calendar section'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_address',
            field=models.EmailField(blank=True, default='', help_text='Contact email address (displayed site-wide and used for contact form)', max_length=254),
        ),
    ]
