# Generated by Django 4.2.28 on 2026-02-21 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0029_extend_site_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterHistoryBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this backup', max_length=200)),
                ('backup_type', models.CharField(choices=[('pre_import', 'Before Import'), ('pre_clear', 'Before Clear All'), ('manual', 'Manual Backup')], default='pre_import', max_length=20)),
                ('data', models.JSONField(help_text='Serialized backup of all history sections')),
                ('section_count', models.PositiveIntegerField(default=0, help_text='Number of sections in this backup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_backups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chapter History Backup',
                'verbose_name_plural': 'Chapter History Backups',
                'ordering': ['-created_at'],
            },
        ),
    ]
