# Generated by Django 4.2.28 on 2026-03-05 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0030_history_backup_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Browser session key', max_length=40, unique=True)),
                ('consent_level', models.CharField(choices=[('essential', 'Essential Only'), ('functional', 'Essential + Functional'), ('analytics', 'Essential + Functional + Analytics'), ('all', 'All Cookies')], default='essential', max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('essential_cookies', models.BooleanField(default=True)),
                ('functional_cookies', models.BooleanField(default=False)),
                ('analytics_cookies', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookie_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cookie Consent',
                'verbose_name_plural': 'Cookie Consents',
                'ordering': ['-consent_date'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, help_text='URL path visited', max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('session_key', models.CharField(blank=True, default='', help_text='Session key (hashed for privacy)', max_length=40)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('ip_hash', models.CharField(blank=True, default='', help_text='Hashed IP for privacy (not reversible)', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_code', models.IntegerField(default=200)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, help_text='Logged in user (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['path', '-timestamp'], name='pages_pagev_path_761207_idx'), models.Index(fields=['-timestamp'], name='pages_pagev_timesta_3cebe7_idx'), models.Index(fields=['user', '-timestamp'], name='pages_pagev_user_id_fd0255_idx')],
            },
        ),
    ]
