# Generated by Django 4.2.28 on 2026-03-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0031_analytics_gdpr"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="last_seen",
            field=models.DateTimeField(
                blank=True,
                help_text="Last activity timestamp for online status",
                null=True,
            ),
        ),
    ]
