# Generated by Django 4.2.28 on 2026-03-09 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0032_add_last_seen_to_memberprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Explain what members are voting on",
                    ),
                ),
                (
                    "poll_type",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting Poll"),
                            ("general", "General Poll"),
                            ("election", "Election"),
                            ("motion", "Motion Vote"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="If true, individual votes are not recorded",
                    ),
                ),
                (
                    "show_results_during",
                    models.BooleanField(
                        default=True, help_text="Show live results while voting is open"
                    ),
                ),
                (
                    "allow_multiple",
                    models.BooleanField(
                        default=False, help_text="Allow selecting multiple options"
                    ),
                ),
                (
                    "max_selections",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum selections if multiple allowed"
                    ),
                ),
                (
                    "financial_only",
                    models.BooleanField(
                        default=False, help_text="Only financial members can vote"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, help_text="Leave blank for no deadline", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Poll",
                "verbose_name_plural": "Polls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="pages.poll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poll Option",
                "verbose_name_plural": "Poll Options",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ZoomMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "meeting_number",
                    models.CharField(
                        help_text="Zoom Meeting ID (e.g., 123-456-789)", max_length=50
                    ),
                ),
                (
                    "meeting_password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Meeting password (if required)",
                        max_length=50,
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Expected meeting duration in minutes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "members_only",
                    models.BooleanField(
                        default=True, help_text="Only logged-in members can join"
                    ),
                ),
                (
                    "financial_only",
                    models.BooleanField(
                        default=False, help_text="Only financial members can join"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to an event (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zoom_meetings",
                        to="pages.event",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zoom Meeting",
                "verbose_name_plural": "Zoom Meetings",
                "ordering": ["-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="ZoomConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sdk_key",
                    models.CharField(
                        help_text="Zoom Meeting SDK Key (Client ID)", max_length=255
                    ),
                ),
                (
                    "sdk_secret",
                    models.CharField(
                        help_text="Zoom Meeting SDK Secret (Client Secret)",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        help_text="Admin who configured this",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zoom_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zoom Configuration",
                "verbose_name_plural": "Zoom Configurations",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="pages.polloption",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="pages.poll",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poll_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote",
                "verbose_name_plural": "Votes",
                "ordering": ["-voted_at"],
            },
        ),
        migrations.AddField(
            model_name="poll",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                help_text="Associate with a meeting (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="polls",
                to="pages.zoommeeting",
            ),
        ),
    ]
