# Generated by Django 4.2.28 on 2026-03-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0033_zoom_meetings_and_polls"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zoommeeting",
            options={
                "ordering": ["-scheduled_time"],
                "verbose_name": "Virtual Meeting",
                "verbose_name_plural": "Virtual Meetings",
            },
        ),
        migrations.AddField(
            model_name="zoommeeting",
            name="meeting_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Meeting link for Google Meet, Teams, or other platforms",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="zoommeeting",
            name="platform",
            field=models.CharField(
                choices=[
                    ("zoom", "Zoom (Embedded)"),
                    ("google_meet", "Google Meet"),
                    ("teams", "Microsoft Teams"),
                    ("webex", "Cisco Webex"),
                    ("other", "Other"),
                ],
                default="zoom",
                help_text="Select the meeting platform",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="zoommeeting",
            name="meeting_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Zoom Meeting ID (for Zoom only)",
                max_length=50,
            ),
        ),
    ]
