# Generated by Django 4.2.28 on 2026-03-09 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0034_platform_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingVoteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motion_title",
                    models.CharField(
                        help_text="The motion being voted on", max_length=300
                    ),
                ),
                (
                    "motion_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional details about the motion",
                    ),
                ),
                (
                    "meeting_date",
                    models.DateField(help_text="Date of the meeting/vote"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("tabled", "Tabled"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="passed",
                        max_length=20,
                    ),
                ),
                ("votes_for", models.PositiveIntegerField(default=0)),
                ("votes_against", models.PositiveIntegerField(default=0)),
                ("abstentions", models.PositiveIntegerField(default=0)),
                (
                    "voters_for",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Names of members who voted in favor (comma-separated)",
                    ),
                ),
                (
                    "voters_against",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Names of members who voted against (comma-separated)",
                    ),
                ),
                (
                    "voters_abstained",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Names of members who abstained (comma-separated)",
                    ),
                ),
                (
                    "moved_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of member who made the motion",
                        max_length=100,
                    ),
                ),
                (
                    "seconded_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of member who seconded",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes for the record",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated meeting (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vote_records",
                        to="pages.zoommeeting",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated poll if voted electronically",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vote_records",
                        to="pages.poll",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Vote Record",
                "verbose_name_plural": "Meeting Vote Records",
                "ordering": ["-meeting_date", "-created_at"],
            },
        ),
    ]
