# Generated by Django 4.2.28 on 2026-03-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0035_meeting_vote_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="zoomconfiguration",
            name="oauth_account_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Zoom Account ID for Server-to-Server OAuth",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="zoomconfiguration",
            name="oauth_client_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="OAuth App Client ID (Server-to-Server)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="zoomconfiguration",
            name="oauth_client_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="OAuth App Client Secret (Server-to-Server)",
                max_length=255,
            ),
        ),
    ]
