# Generated by Django 4.2.28 on 2026-03-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0036_add_zoom_oauth_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterleadership",
            name="member",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to member profile (allows member to manage their own photo)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leadership_positions",
                to="pages.memberprofile",
            ),
        ),
    ]
