# Generated by Django 4.2.28 on 2026-03-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0037_chapterleadership_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="boutique_type",
            field=models.CharField(
                choices=[
                    ("internal", "Use Internal Boutique"),
                    ("external", "Link to External Store"),
                ],
                default="internal",
                help_text="Choose between hosting your own boutique or linking to an external store",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="event_tickets_type",
            field=models.CharField(
                choices=[
                    ("internal", "Use Internal Ticketing"),
                    ("external", "Link to External Ticket Site"),
                ],
                default="internal",
                help_text="Choose between hosting your own ticketing or linking to an external site",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="external_store_name",
            field=models.CharField(
                blank=True,
                default="Shop",
                help_text='Text to display for the store link (e.g., "Shop Now", "Visit Our Store")',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="external_store_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of your external e-store (e.g., shopify, etsy, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="external_tickets_name",
            field=models.CharField(
                blank=True,
                default="Buy Tickets",
                help_text='Text to display for the tickets link (e.g., "Get Tickets", "Buy Now")',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="external_tickets_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of your external ticket site (e.g., Eventbrite, Ticketmaster, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="show_event_tickets",
            field=models.BooleanField(
                default=False, help_text="Show the event ticketing section"
            ),
        ),
    ]
