# Generated by Django 4.2.28 on 2026-03-10 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0038_add_boutique_and_ticketing_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(help_text="Name of the event", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Event description and details",
                    ),
                ),
                ("event_date", models.DateField(help_text="Date of the event")),
                ("event_time", models.TimeField(help_text="Start time of the event")),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, help_text="End time (optional)", null=True
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(help_text="Name of the venue", max_length=200),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Full address of the venue", max_length=300
                    ),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=50)),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("general", "General Admission"),
                            ("vip", "VIP"),
                            ("early_bird", "Early Bird"),
                            ("member", "Member Only"),
                            ("group", "Group Package"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price per ticket", max_digits=10
                    ),
                ),
                (
                    "quantity_available",
                    models.PositiveIntegerField(
                        default=0, help_text="Total tickets available for sale"
                    ),
                ),
                (
                    "quantity_sold",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of tickets sold"
                    ),
                ),
                (
                    "max_per_order",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum tickets per order"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Event promotional image",
                        null=True,
                        upload_to="event_tickets/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Active tickets are visible for purchase",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured events appear first"
                    ),
                ),
                (
                    "requires_member",
                    models.BooleanField(
                        default=False, help_text="Only members can purchase"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_tickets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Ticket",
                "verbose_name_plural": "Event Tickets",
                "ordering": ["event_date", "event_time"],
            },
        ),
        migrations.CreateModel(
            name="TicketPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price_per_ticket",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price at time of purchase",
                        max_digits=10,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email for ticket confirmation", max_length=254
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Name on the ticket", max_length=200),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("completed", "Payment Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "stripe_payment_intent",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                (
                    "confirmation_code",
                    models.CharField(
                        help_text="Unique confirmation code", max_length=20, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="pages.eventticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Purchase",
                "verbose_name_plural": "Ticket Purchases",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="pages_ticke_user_id_abbf49_idx",
                    ),
                    models.Index(
                        fields=["email", "-created_at"],
                        name="pages_ticke_email_4d818e_idx",
                    ),
                    models.Index(
                        fields=["confirmation_code"],
                        name="pages_ticke_confirm_b5d03b_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="pages_ticke_status_169bfa_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="eventticket",
            index=models.Index(
                fields=["event_date", "is_active"],
                name="pages_event_event_d_924299_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventticket",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="pages_event_is_acti_ac9b3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventticket",
            index=models.Index(
                fields=["is_featured", "event_date"],
                name="pages_event_is_feat_e0ee54_idx",
            ),
        ),
    ]
