# Generated by Django 4.2.28 on 2026-03-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0040_populate_chatbot_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No Program"),
                    ("bbb", "Bigger & Better Business"),
                    ("education", "Education"),
                    ("social_action", "Social Action"),
                    ("sigma_beta", "Sigma Beta Club"),
                ],
                default="",
                help_text="Tag this photo for a program to show on homepage carousel",
                max_length=20,
            ),
        ),
    ]
